
DISPLAY_WIDTH: int = 1300
DISPLAY_HEIGHT: int = 1000

TOOLS_PART_WIDTH: int = 300
PAINT_PART_SIZE = (DISPLAY_WIDTH - TOOLS_PART_WIDTH, DISPLAY_HEIGHT)


BUTTON_START_NAME: str = "Start"
BUTTON_STOP_NAME: str = "Stop"
BUTTON_NEW_MAP_NAME: str = "New map"
BUTTON_CALCULATE_PATH_NAME: str = "Calculate path"

SLD_ANTS_COUNT_RANGE = (2, 200)
ANTS_COUNT_DEFAULT: int = 50
POSITION_ANTS_COUNT_DEFAULT: int = 24
SLD_ANTS_COUNT_LABEL_NAME: str = "Ants count"
SLD_ANTS_COUNT_LABEL_MIN: str = str(SLD_ANTS_COUNT_RANGE[0])
SLD_ANTS_COUNT_LABEL_MAX: str = str(SLD_ANTS_COUNT_RANGE[1])

SLD_ALPHA_RANGE = (0.1, 3.0)
ALPHA_DEFAULT: float = 1.0
POSITION_ALPHA_DEFAULT: int = 33
SLD_ALPHA_LABEL_NAME: str = "Alpha"
SLD_ALPHA_LABEL_MIN: str = str(SLD_ALPHA_RANGE[0])
SLD_ALPHA_LABEL_MAX: str = str(SLD_ALPHA_RANGE[1])

SLD_BETA_RANGE = (0.1, 3.0)
BETA_DEFAULT: float = 1.0
POSITION_BETA_DEFAULT: int = 33
SLD_BETA_LABEL_NAME: str = "Beta"
SLD_BETA_LABEL_MIN: str = str(SLD_BETA_RANGE[0])
SLD_BETA_LABEL_MAX: str = str(SLD_BETA_RANGE[1])

SLD_VAPORIZE_RANGE = (0.0, 1.0)
VAPORIZE_DEFAULT: float = 0.5
POSITION_VAPORIZE_DEFAULT: int = 50
SLD_VAPORIZE_LABEL_NAME: str = "Vaporization"
SLD_VAPORIZE_LABEL_MIN: str = str(SLD_VAPORIZE_RANGE[0])
SLD_VAPORIZE_LABEL_MAX: str = str(SLD_VAPORIZE_RANGE[1])

SLD_RANDOM_FACTOR_RANGE = (0.0, 1.0)
RANDOM_FACTOR_DEFAULT: float = 0.0
POSITION_RANDOM_FACTOR_DEFAULT: int = 0
SLD_RANDOM_FACTOR_LABEL_NAME: str = "Random factor"
SLD_RANDOM_FACTOR_LABEL_MIN: str = str(SLD_RANDOM_FACTOR_RANGE[0])
SLD_RANDOM_FACTOR_LABEL_MAX: str = str(SLD_RANDOM_FACTOR_RANGE[1])

SLD_SPEED_FRAME_RANGE = (10, 1000)
SPEED_FRAME_DEFAULT: int = 59
POSITION_SPEED_FRAME_DEFAULT: int = 4
SLD_SPEED_FRAME_LABEL_NAME: str = "Delay between iterations in ms"
SLD_SPEED_FRAME_LABEL_MIN: str = str(SLD_SPEED_FRAME_RANGE[0])
SLD_SPEED_FRAME_LABEL_MAX: str = str(SLD_SPEED_FRAME_RANGE[1])

SLD_NODES_COUNT_RANGE = (2, 150)
NODES_COUNT_DEFAULT: int = 10
POSITION_NODES_COUNT_DEFAULT: int = 9
SLD_NODES_COUNT_LABEL_NAME: str = "Nodes"
SLD_NODES_COUNT_LABEL_MIN: str = str(SLD_NODES_COUNT_RANGE[0])
SLD_NODES_COUNT_LABEL_MAX: str = str(SLD_NODES_COUNT_RANGE[1])

SLD_ITERATIONS_RANGE = (10, 1000)
ITERATIONS_DEFAULT: int = 300
POSITION_ITERATIONS_RANGE_DEFAULT: int = 29
SLD_ITERATIONS_LABEL_NAME: str = "Iterations"
SLD_ITERATIONS_LABEL_MIN: str = str(SLD_ITERATIONS_RANGE[0])
SLD_ITERATIONS_LABEL_MAX: str = str(SLD_ITERATIONS_RANGE[1])

ITERATIONS_LABEL_NAME: str = "Iterations:"
ITERATIONS_LABEL_DEFAULT: str = "inf"

MIN_PATH_LABEL_NAME: str = "Path length:"
MIN_PATH_LABEL_DEFAULT: str = "inf"

CALCULATED_PATH_LABEL_NAME: str = "Min path length:"
CALCULATED_PATH_LABEL_DEFAULT: str = "inf"

SLD_SIZE = (200, 30)
BUTTON_SIZE = (100, 30)
LABEL_MIN_MAX_SIZE = (SLD_SIZE[0] // 4, SLD_SIZE[1] // 2)
LABEL_VALUE_SIZE = (SLD_SIZE[0] // 2, SLD_SIZE[1] // 2)
